export const MessageData = [
  {
    id: "1",
    name: "John Doe",
    message: "Hi",
    time: "12:00 AM",
  },
  {
    id: "2",
    name: "John Doe",
    message: "Hello",
    time: "09:42 AM",
  },
  {
    id: "1",
    name: "John Doe",
    message: "How are You?",
    time: "12:00 AM",
  },
  {
    id: "2",
    name: "John Doe",
    message: "Doing Good! What about you?",
    time: "12:00 AM",
  },
  {
    id: "1",
    name: "John Doe",
    message: "Nothing Much! Just chilling! What about you?",
    time: "09:42 AM",
  },
  {
    id: "2",
    name: "John Doe",
    message: "Lets meet at 5 PM today",
    time: "12:00 AM",
  },
  {
    id: "1",
    name: "John Doe",
    message: "Ok",
    time: "12:00 AM",
  },
  {
    id: "2",
    name: "John Doe",
    message: "And bring the files with you",
    time: "09:42 AM",
  },
  {
    id: "1",
    name: "John Doe",
    message: "Sure!",
    time: "12:00 AM",
  },
  {
    id: "1",
    name: "John Doe",
    message: "Hi",
    time: "12:00 AM",
  },
  {
    id: "2",
    name: "John Doe",
    message: "Hello",
    time: "09:42 AM",
  },
  {
    id: "1",
    name: "John Doe",
    message: "How are You?",
    time: "12:00 AM",
  },
  {
    id: "2",
    name: "John Doe",
    message: "Doing Good! What about you?",
    time: "12:00 AM",
  },
  {
    id: "1",
    name: "John Doe",
    message: "Nothing Much! Just chilling! What about you?",
    time: "09:42 AM",
  },
  {
    id: "2",
    name: "John Doe",
    message: "Lets meet at 5 PM today",
    time: "12:00 AM",
  },
  {
    id: "1",
    name: "John Doe",
    message: "Ok",
    time: "12:00 AM",
  },
  {
    id: "2",
    name: "John Doe",
    message: "And bring the files with you",
    time: "09:42 AM",
  },
  {
    id: "1",
    name: "John Doe",
    message: "Sure!",
    time: "12:00 AM",
  },
  {
    id: "1",
    name: "John Doe",
    message: "Hi",
    time: "12:00 AM",
  },
  {
    id: "2",
    name: "John Doe",
    message: "Hello",
    time: "09:42 AM",
  },
  {
    id: "1",
    name: "John Doe",
    message: "How are You?",
    time: "12:00 AM",
  },
  {
    id: "2",
    name: "John Doe",
    message: "Doing Good! What about you?",
    time: "12:00 AM",
  },
  {
    id: "1",
    name: "John Doe",
    message: "Nothing Much! Just chilling! What about you?",
    time: "09:42 AM",
  },
  {
    id: "2",
    name: "John Doe",
    message: "Lets meet at 5 PM today",
    time: "12:00 AM",
  },
  {
    id: "1",
    name: "John Doe",
    message: "Ok",
    time: "12:00 AM",
  },
  {
    id: "2",
    name: "John Doe",
    message: "And bring the files with you",
    time: "09:42 AM",
  },
  {
    id: "1",
    name: "John Doe",
    message: "Sure!",
    time: "12:00 AM",
  },
];